# Project information
site_name: Observatory Game Website
site_description: Observatory Game Website description
site_author: Tanis Webb
site_url: https://observatory-contact.netlify.app/

# Copyright
copyright: >
    Copyright &copy; 2024 Tanis Webb </br>
    <a href="#__consent">Change cookie settings</a>

# Repository
repo_name: observatory-game
# repo_url: https://github.com/stockbrot/observatory-game

# Configuration
docs_dir: docs
theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  name: material
  language: en
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  features:
    - navigation.indexes
    # instant not compatible with language switching. :(
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.integrate
    - header.autohide
    # - toc.follow
  font:
    # text: Work Sans
    # text: Raleway
    text: Poppins
    code: Ubuntu Mono
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: _
      title: 'On this page:'
      permalink_title: 'Anchor link to this section for reference'

plugins:
  # Translation is broken due to "i18n is not installed" on netlify
  # - i18n:
  #     docs_structure: folder
  #     languages:
  #       - locale: en
  #         default: true
  #         name: English
  #         build: true
  #       - locale: de
  #         name: Deutsch
  #         build: true
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        # - de
  - blog

# Customization
extra_css:
  - assets/css/custom.css
extra:
  # Social links at the bottom right corner
  social:
    - icon: fontawesome/brands/itch-io
      link: https://doctororbit.itch.io/
  # Toggle for switching languages
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: Deutsch
  #     link: /de/
  #     lang: de

# Page tree
nav:
  - Home: index.md
  - Game:
    - Overview: game/about.md
    - Adding: game/adding.md
  - Info:
    - About Me: info/about.md
    - About Website: info/website.md
  - Blog: 
    - blog/index.md
