# Project information
site_name: Observatory Game Website
site_description: Observatory Game Website description
site_author: Tanis Webb
site_url: https://observatory-contact.netlify.app/

# Copyright
copyright: Copyright &copy; 2024 Tanis Webb

# Repository
repo_name: observatory-game
# repo_url: https://github.com/stockbrot/observatory-game

# Configuration
docs_dir: docs
theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  language: en
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  features:
    - navigation.indexes
    # instant not compatible with language switching. :(
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: _

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - de

# Customization
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - assets/css/custom.css
extra:
  social:
    - icon: fontawesome/brands/itch-io
      link: https://doctororbit.itch.io/
  alternate:
    - name: English
      link: /
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

# Page tree
nav:
  - Home: index.md
  - Game:
    - game/index.md
    - Overview: game/about.md
  - Info:
    - info/index.md
    - About Me: info/about.md
    - About Website: info/website.md
