# Project information
site_name: Observatory Game Website
site_description: Observatory Game Website description
site_author: Tanis Webb
site_url: https://observatory-contact.netlify.app/

# Copyright
copyright: >
    Copyright &copy; 2024 Tanis Webb </br>
    <a href="#__consent">Change cookie settings</a>

# Repository
repo_name: observatory-game
# repo_url: https://github.com/stockbrot/observatory-game

# Configuration
docs_dir: docs
theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  language: en
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  features:
    # - navigation.indexes
    # instant not compatible with language switching. :(
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    # - toc.follow
  font:
    # text: Work Sans
    # text: Raleway
    text: Poppins
    code: Ubuntu Mono
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: _
      title: 'On this page:'
      permalink_title: 'Anchor link to this section for reference'

plugins:
  # Translation is broken due to "i18n is not installed" on netlify
  # - i18n:
  #     docs_structure: folder
  #     languages:
  #       - locale: en
  #         default: true
  #         name: English
  #         build: true
  #       - locale: de
  #         name: Deutsch
  #         build: true
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        # - de
  - blog

# Customization
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - assets/css/custom.css
extra:
  analytics:
    provider: google
    property: G-1WR0665CD6
  consent:
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  # Social links at the bottom right corner
  social:
    - icon: fontawesome/brands/itch-io
      link: https://doctororbit.itch.io/
  # Toggle for switching languages
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en
  #   - name: Deutsch
  #     link: /de/
  #     lang: de

# Page tree
nav:
  - Home: index.md
  - Game:
    - Overview: game/about.md
    - Adding: game/adding.md
  - Info:
    - About Me: info/about.md
    - About Website: info/website.md
