authors:
  stockbrot:
    name: Tanis W.        # Author name
    description: Creator # Author description
    avatar: /assets/images/pfp.png         # Author avatar
    url: https://doctororbit.itch.io            # Author website URL